// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiWDmd6T_0dAtAxnL8C1Wk6sLnS41t-o',
    appId: '1:689203231897:web:18d2e70a9cf860d86d0c08',
    messagingSenderId: '689203231897',
    projectId: 'anhfirebase-96234',
    authDomain: 'anhfirebase-96234.firebaseapp.com',
    storageBucket: 'anhfirebase-96234.firebasestorage.app',
    measurementId: 'G-8ZL2Q4EE55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrAPmVVXaGQLCOBkRGneLXDeXxONpyMQ',
    appId: '1:689203231897:android:c5b1d167d2d5b0056d0c08',
    messagingSenderId: '689203231897',
    projectId: 'anhfirebase-96234',
    storageBucket: 'anhfirebase-96234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBPiH1o-nNFmtyVYYF3yAEX876OfiAqQ',
    appId: '1:689203231897:ios:485f1ed1a35d45f96d0c08',
    messagingSenderId: '689203231897',
    projectId: 'anhfirebase-96234',
    storageBucket: 'anhfirebase-96234.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBPiH1o-nNFmtyVYYF3yAEX876OfiAqQ',
    appId: '1:689203231897:ios:485f1ed1a35d45f96d0c08',
    messagingSenderId: '689203231897',
    projectId: 'anhfirebase-96234',
    storageBucket: 'anhfirebase-96234.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiWDmd6T_0dAtAxnL8C1Wk6sLnS41t-o',
    appId: '1:689203231897:web:9b460bcef300c5b16d0c08',
    messagingSenderId: '689203231897',
    projectId: 'anhfirebase-96234',
    authDomain: 'anhfirebase-96234.firebaseapp.com',
    storageBucket: 'anhfirebase-96234.firebasestorage.app',
    measurementId: 'G-NKKWH36QD6',
  );
}
